### ISSUE TITLE
Review Joss Paper Tulio 

### ISSUE THREAD

**Issue by tuliofalmeida** [tne-lab/py-behav-box-v2#68]
Hello, first of all it's a pleasure to [review](https://github.com/openjournals/joss-reviews/issues/6515) your work! 

So, so far I'm checking it alongside with experimentalist friend that doesn't know how to code but would like to use the library.
I would like to know who is the target of your library? Because I want to test it with this friend that will need it to plan the experiments.

In the first testing session, we did today was frustrating to him (basic python level) that you can't do everything trough the interface. We tried to follow the tutorial to add the webcam, and he got lost in creating the AdresseFile, is not clear in the tutorial how you switch to the GUI to create the file. 

If you are aiming advance people in python already adapted to do this setups, I'll change my perspective.

Thanks

**Comment by theonlydvr** [comment]
I'd say my intended target was generally experimentalists who had some code familiarity (so some basic Python experience at least). However, I don't think that group is necessarily that different from experimentalists who have to use existing behavioral systems (Med Associates, ABET, etc) because they often have their own custom language-like structures which have a large learning curve. Generally, I'd like to make the system workable for those users at least as far as being able to relatively easily setup an existing task on a new rig.

So given what you're describing, it sounds like the frustrating portion was that the AddressFile and Protocol creation had to happen in a text editor rather than through a GUI tool? I think it could be reasonable to add an interface to create new AddressFiles or protocols for an input task. Do you think that would address the need?

I'm very happy to add more features along these lines to streamline the process for this sort of user.

**Comment by tuliofalmeida** [comment]
Perfect. First was not that clear that was necessary to do this separated in text file. But, this solution that you propose is really good and maybe can overcome one future problem with paths and files allocated in wrong folders. So you agree that we can follow this line of thinking for the testing ?

**Comment by theonlydvr** [comment]
Definitely a good line of thinking for testing, the combination of your expertise with an experimentalist user will be very helpful. On the earlier point, I'll make sure to clarify the existing documentation and workshop the GUI option.

**Comment by theonlydvr** [comment]
I just pushed some code to the dev branch that provides an option for creating AddressFiles and Protocols using a GUI (they can be accessed from the file menu). I'm still working on adding documentation for the feature but let me know if it lines up with what you thought might be helpful.

**Comment by theonlydvr** [comment]
A few changes were made to the VideoSource on a recent commit that will avoid some bugs you would likely have come across.

**Comment by tuliofalmeida** [comment]
Hey, I tested the new feature I think that will be way more easy to non-coders. I'll finish the review, but I'll suggest to my lab mates to use it in the next experiments.
