### ISSUE TITLE
Add example/tutorial that doesn't require hardware

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#76]
A major draw of this software is that it is hardware agnostic. It would be easier to get started/evaluate/become familiar with the software if there were a tutorial that does not require Lafayette Instruments hardware and WhiskerServer as the current tutorial does. 

Would it be possible to create an tutorial with an example task that only uses the pygame GUI as a source of events? Or perhaps a tutorial that connects to simulated hardware that provides events? 

There are a lot of features to explore and learn about when it comes to creating task logic or extra GUI widgets etc. Right now not having the same hardware as the tutorial is a barrier.

**Comment by theonlydvr** [comment]
So by default, tasks in pybehave can be controlled directly from the pygame GUI so the tasks in the [example repo](https://github.com/tne-lab/example-tasks) should be testable without any hardware. I will add a tutorial to make this explicit though because I don't think I actually made this ability clear anywhere in the documentation come to think of it.

**Comment by theonlydvr** [comment]
I added some more explicit language throughout the documentation and a few examples in a "no hardware" tutorial
