### ISSUE TITLE
Windows dependency

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#77]
I suspect by the inclusion of a .bat file in the repository, the software is primarily intended for and/or tested on a Windows machine? If so, please mention in the documentation that it is for Windows only. If it is supposed to be a cross-platform software, mention the extent that you have tested the compatibility. I personally failed to get it installed on a Mac, but can open a separate issue for us to try and resolve if you intend on offering support. No pressure to offer cross-platform support, just wanting the dependencies to clear in the documentation (as per JOSS review criteria).

**Comment by theonlydvr** [comment]
It looks like the language about only being tested on Windows disappeared from the docs when I updated them for the JOSS submission... I would like to offer cross-platform support, I just haven't tested it quite yet. I do know that the full install will not work on mac since some of the supported sources (Whisker) are Windows only. So an issue showing what isn't working on a Mac install would definitely be helpful.
