### ISSUE TITLE
parameter updates from user within a session

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#80]
I am using the subject configuration widget to adjust some parameters while the task is running. Value changes I make are reflected in task logic like I want, however there is no record of the value changes in the data log. 

I suspect I may be abusing the configurator by making adjustments while the task is running and instead should add the functionality to the pygame taskGUI? 

A couple of suggestions:

- in the docs, clarify the best practice for achieving this in-session variable adjustments
- if using the configuration widget is okay, log changes that happen during a session (currently it only shows the starting values in the log)
- if configuration widget is not the preferred method
    - disable input to the configuration widget when a session is running
    - relabel the widget from "Subject Configuration" to "Subject Start Configuration"?
    - add another [default element](https://py-behav-box-v2.readthedocs.io/en/latest/guis/#default-elements)  that can take an input and has a "set" or "update" type button for submitting a change to a value?

**Comment by theonlydvr** [comment]
That is somewhat unintentional behavior because those subject configuration values are serialized and loaded when the task is created the next time. However, I do think the feature would be useful especially during development. I think the best approach would be to allow for use of the Subject Configuration while a task is running but make the user explicitly save the defaults for a subject (if they want to). I think this would be better than cluttering the task GUI with a bunch of setter/update buttons.

**Comment by theonlydvr** [comment]
I've added some documentation and a more intentional version of this feature on 75ad0abd51ccf66ecff02e637e4cfd33554d08cb.

**Comment by sappelhoff** [comment]
@alustig3 could you please check whether you are satisfied with the changes that @theonlydvr mentions in https://github.com/tne-lab/py-behav-box-v2/issues/80#issuecomment-2088708062?

This is one of two last remaining issues that seem to be open on your [JOSS checklist](https://github.com/openjournals/joss-reviews/issues/6515#issuecomment-2013016065).

**Comment by theonlydvr** [comment]
The buttons have been made more explicit on b0b66a90ddde7e91c7a505edc9b76ae91c1eb72e
